import {Component, EventEmitter, Output} from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [],
  templateUrl: './input-button-unit.component.html',
  styleUrl: './input-button-unit.component.scss'
})


export class InputButtonUnitComponent {
  title = 'Get Started';

  @Output() submit: EventEmitter<string> = new EventEmitter<string>();

  constructor() {}

  generateTitle() : string {
    return 'This title was generated by a method';
  }

  changeTitle(newTitle: string) {
    this.submit.emit(newTitle);
  }

  submitValue(event: Event) {
    return (event.target as HTMLInputElement).value;
  }
}
